### PR TITLE
Proposal: Convert Resource Agent API to markdown

### PR DESCRIPTION
**Pull request by krig**
Removes the docbook and text format documents describing the
Resource Agent API, and replaces them with a Markdown document.

The benefits of using Markdown over the two previous formats is
that a single source document covers all use cases, making it
easier for people to submit changes to the API, and avoids
potential differences between the document formats.

There are other document markup formats, but none are as widely used
as Markdown.

### CODE REVIEW

**Comment by fghaas** [comment]
I have no objections to converting this to Markdown, but others are probably better qualified to comment on whether this API definition (or at least parts thereof) isn't obsolete to begin with...

**Comment by krig** [comment]
My reason for wanting to convert it to markdown is that I want to start proposing changes to it, and I don't want to edit the docbook and txt documents... :)

**Comment by krig** [comment]
Another option would be to rewrite it to the RFC format. I don't know if there has been any attempt at creating a RFC for the OCF standard? That's a LOT more work, though. (Someone SHOULD do that work. Unfortunately, no one MUST do that work, so I doubt it would get done. Plus, it'd need to get updated to what is the de-facto state of resource-agents now, and there's all the things that should be integrated from fence-agents etc.)

**Comment by beekhof** [comment]
Readable /and/ avoids duplication - thats an easy decision I reckon.
If someone objects in the future they are welcome to track me down but I don't see any cause to hold you up.

**Comment by lge** [comment]
> Merged #1.

Thanks!

```
Lars
```

**Pull request merged**
