### PR TITLE
Replace DTD version of schema with Relax-NG

### PR DESCRIPTION
**Pull request by marxsk**

### CODE REVIEW

**Comment by jnpkrn** [comment]
Was RNG counterpart obtained via an automated tool/which or by hand crafting it?
It would be useful to have this captured in the commit as well, for posterity.

**Comment by marxsk** [comment]
@jnpkrn It was done manually. I was not aware of any automatic tools that can do that.

**Comment by dmuhamedagic** [comment]
great! btw, do we need dtd for some applications or is it
completely obsoleted by rng?

**Comment by marxsk** [comment]
@dmuhamedagic 

imho DTD is still used in some places but usually it is not linked to this repo. It might be good idea to create branches or releases, so it can be accessed when needed. But for "upstream" there is no need to use other than last version.

**Comment by krig** [comment]
Looks good to me :)

**Comment by marxsk** [comment]
@krig The policy agreed on few years ago is that we wait 14 days for comments (and rejects). So far, we are good :) For more important changes (e.g. extensions), they will post also on mailing-lists.

**Comment by krig** [comment]
@marxsk Sounds good, yes. Looking at the Relax-NG, there are already some obvious things that are de-facto standards that we should add. For example the `require` flag for parameters. But better to do that in a separate PR perhaps.

**Comment by kgaillot** [comment]
> @marxsk Sounds good, yes. Looking at the Relax-NG, there are already some obvious things that are de-facto standards that we should add. For example the require flag for parameters. But better to do that in a separate PR perhaps.

Agreed, that should be a separate PR, with the corresponding changes to the text of the RA standard as well. I think a good first step (after this PR) would be to remove the "draft" status of the 2002 OCF 1.0 standard :-) then incorporate the de-facto standards as an OCF 1.1 release, before thinking about bigger changes.

**Comment by jnpkrn** [comment]
On 11/09/17 13:38 +0000, marxsk wrote:
> @jnpkrn It was done manually. I was not aware of any automatic tools
> that can do that. 

One of the tools allegedly able to do that is trang
(http://www.thaiopensource.com/relaxng/trang.html).

Sadly, I cannot get pass this issue:

```
$ trang -I dtd -O rng ra-api-1.dtd ra-api-1.rng
fatal: exception "java.io.CharConversionException" thrown: invalid text declaration
```

-- 
Jan (Poki)

**Pull request merged**
